### ISSUE TITLE
Renew token failing for push notifications

### ISSUE THREAD

**Issue by tomazmla** [bropat/ioBroker.eufy-security#10]
hi bropat,

The push notification token has expired and the renewal is failing for me. Is there a solution or workaround for this?
Logs:
2020-11-30 12:39:15.168 - debug: eufy-security.0 (5541) handleDevices(): count: 1
2020-11-30 12:39:15.172 - debug: eufy-security.0 (5541) onConnect(): save api_base - api_base: https://security-app-eu.eufylife.com/v1
2020-11-30 12:39:15.174 - debug: eufy-security.0 (5541) onConnect(): save token and expiration - token: xxxxx token_expiration: Wed Dec 30 2020 12:36:58 GMT+0100 (Central European Standard Time)
2020-11-30 12:39:15.184 - debug: eufy-security.0 (5541) EufySecurity.registerPushNotifications(): Renew push credentials...
2020-11-30 12:39:15.228 - info: eufy-security.0 (5541) state eufy-security.0.T8010XXXXXXXXXX.cameras.T8210XXXXXXXXXX.last_camera_url changed: https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/thumb/2020/xx/xx/station/T8010XXXXXXXXXX/xxxxxxxxx.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxx&X-Amz-Date=20201130T113915Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxx (ack = true)
2020-11-30 12:39:15.321 - error: eufy-security.0 (5541) PushRegisterService.renewFidToken(): error: Error: Request failed with status code 400
2020-11-30 12:39:15.322 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-11-30 12:39:15.322 - error: eufy-security.0 (5541) unhandled promise rejection: FID Token renewal failed with error: Error: Request failed with status code 400
2020-11-30 12:39:15.323 - error: eufy-security.0 (5541) Error: FID Token renewal failed with error: Error: Request failed with status code 400
at PushRegisterService. (/opt/iobroker/node_modules/iobroker.eufy-security/build/lib/eufy-security/push/register.js:106:23)
at Generator.throw ()
at rejected (/opt/iobroker/node_modules/iobroker.eufy-security/build/lib/eufy-security/push/register.js:6:65)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-30 12:39:15.325 - info: eufy-security.0 (5541) Disconnect from station T8010XXXXXXXXXX.

Thanks,
tomazmla

**Comment by bropat** [comment]
Hi @tomazmla,

i pushed a new version in the develop branch. Please try that version and let me know.

**Comment by tomazmla** [comment]
Hi blopat,

sorry for not getting back to you earlier as I was testing the last update. I noticed few times the error below but could not tell when that happens:
2020-12-02 18:28:57.914 - error: eufy-security.0 (9683) API.updateDeviceInfo(): stations - error: {"message":"getaddrinfo EAI_AGAIN security-app-eu.eufylife.com security-app-eu.eufylife.com:443","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN security-app-eu.eufylife.com security-app-eu.eufylife.com:443\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)","config":{"url":"app/get_hub_list","method":"post","headers":{"Accept":"application/json, text/plain, */*","X-Auth-Token":"xxxxx","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/0.21.0"},"baseURL":"https://security-app-eu.eufylife.com/v1","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"code":"EAI_AGAIN"}
2020-12-02 18:28:57.915 - error: eufy-security.0 (9683) API.updateDeviceInfo(): Status return code not 200 (status: undefined text: undefined
2020-12-02 18:29:17.933 - error: eufy-security.0 (9683) API.updateDeviceInfo(): devices - error: {"message":"getaddrinfo EAI_AGAIN security-app-eu.eufylife.com security-app-eu.eufylife.com:443","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN security-app-eu.eufylife.com security-app-eu.eufylife.com:443\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)","config":{"url":"app/get_devs_list","method":"post","headers":{"Accept":"application/json, text/plain, */*","X-Auth-Token":"xxxxx","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/0.21.0"},"baseURL":"https://security-app-eu.eufylife.com/v1","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"code":"EAI_AGAIN"}
2020-12-02 18:29:17.933 - error: eufy-security.0 (9683) API.updateDeviceInfo(): Status return code not 200 (status: undefined text: undefined

And it didn't appear yesterday. But maybe you solved that in the stable release anyway...

Regards,
tomazmla

**Comment by bropat** [comment]
Hi @tomazmla,

EAI_AGAIN is a DNS search timeup error, meaning that it is a network connectivity error or proxy error. It's not a specific error of the Adapter.

The push notification token has a duration of 7 days, so if for more than 7 days you do not get an error with push notifications and continue to receive notifications, the problem is solved.

I would say to wait a few more days before closing this issue. ok?

**Comment by tomazmla** [comment]
Hi @bropat,

Agree, let's wait for few more days to confirm bug resolved.

Thanks,
tomazmla

**Comment by bropat** [comment]
@tomazmla I think the Bug is solved :)

**Comment by tomazmla** [comment]
Agree, thanks!
