### ISSUE TITLE
Unable to load instance, getting error

### ISSUE THREAD

**Issue by Snuffy2** [bropat/ioBroker.eufy-security#105]
When I try to enable the Eufy Security Instance, It won't load and it shows the error below. Any suggestions on how to troubleshoot or fix?

`
2021-03-31 20:32:02.720 - warn: web.0 (2058) Terminated (-100): Without reason
2021-03-31 20:32:02.741 - info: host.f1c878cb-iobroker instance system.adapter.eufy-security.0 started with pid 2877
2021-03-31 20:32:03.239 - info: web.0 (2058) terminated http server on port 8082
2021-03-31 20:32:03.281 - info: host.f1c878cb-iobroker instance system.adapter.web.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
2021-03-31 20:32:03.282 - info: host.f1c878cb-iobroker Restart adapter system.adapter.web.0 because enabled
2021-03-31 20:32:04.301 - info: host.f1c878cb-iobroker instance system.adapter.web.0 started with pid 2888

2021-03-31 20:32:04.428 - info: eufy-security.0 (2877) starting. Version 0.5.0 in /data/iobroker/node_modules/iobroker.eufy-security, node: v12.21.0, js-controller: 3.2.16
2021-03-31 20:32:04.647 - error: eufy-security.0 (2877) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-03-31 20:32:04.648 - error: eufy-security.0 (2877) unhandled promise rejection: Cannot read property 'val' of null
2021-03-31 20:32:04.650 - error: eufy-security.0 (2877) TypeError: Cannot read property 'val' of null
at EufySecurity. (/data/iobroker/node_modules/iobroker.eufy-security/build/main.js:317:27)
at Generator.next ()
at fulfilled (/data/iobroker/node_modules/iobroker.eufy-security/build/main.js:27:58)
2021-03-31 20:32:04.651 - error: eufy-security.0 (2877) Cannot read property 'val' of null

2021-03-31 20:32:04.670 - info: eufy-security.0 (2877) terminating
2021-03-31 20:32:04.671 - warn: eufy-security.0 (2877) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-03-31 20:32:05.228 - error: host.f1c878cb-iobroker instance system.adapter.eufy-security.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-03-31 20:32:05.229 - info: host.f1c878cb-iobroker Restart adapter system.adapter.eufy-security.0 because enabled
2021-03-31 20:32:06.011 - info: web.0 (2888) starting. Version 3.3.0 in /data/iobroker/node_modules/iobroker.web, node: v12.21.0, js-controller: 3.2.16
2021-03-31 20:32:06.308 - info: web.0 (2888) socket.io server listening on port 8082

2021-03-31 20:32:06.326 - info: web.0 (2888) Connect extension "eufy-security/build/lib/web.js"
2021-03-31 20:32:06.334 - info: web.0 (2888) http server listening on port 8082
`

**Versions:**  
Running ioBroker as Supervisor Add-On in Home Assistant
 - Adapter version: 0.5.0
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: RPi4 Buster

**Comment by Snuffy2** [comment]
0.5.1 resolved my issue, thanks!
