### ISSUE TITLE
 this.hub.devices is not iterable

### ISSUE THREAD

**Issue by 89jd** [bropat/ioBroker.eufy-security#115]
Added eufy, getting red circle; only connected to eufy security (not heartbeat / p2p). Logs are below

```
web.0 | 2021-04-06 17:56:41.984 | info | (1217) http server listening on port 8082
-- | -- | -- | --
web.0 | 2021-04-06 17:56:41.978 | info | (1217) Connect extension "eufy-security/build/lib/web.js"
web.0 | 2021-04-06 17:56:41.958 | info | (1217) socket.io server listening on port 8082
host.fe08c82c2656 | 2021-04-06 17:56:41.956 | info | Restart adapter system.adapter.eufy-security.0 because enabled
host.fe08c82c2656 | 2021-04-06 17:56:41.955 | error | instance system.adapter.eufy-security.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
web.0 | 2021-04-06 17:56:41.690 | info | (1217) starting. Version 3.3.0 in /opt/iobroker/node_modules/iobroker.web, node: v12.22.0, js-controller: 3.2.16
eufy-security.0 | 2021-04-06 17:56:41.386 | warn | (1206) Terminated (UNCAUGHT_EXCEPTION): Without reason
eufy-security.0 | 2021-04-06 17:56:41.382 | info | (1206) terminating
eufy-security.0 | 2021-04-06 17:56:41.380 | info | (1206) Disconnect from station <ID>.
eufy-security.0 | 2021-04-06 17:56:41.355 | error | (1206) this.hub.devices is not iterable
eufy-security.0 | 2021-04-06 17:56:41.355 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
eufy-security.0 | 2021-04-06 17:56:41.355 | error | at fulfilled (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:5:58)
eufy-security.0 | 2021-04-06 17:56:41.355 | error | at Generator.next (<anonymous>)
eufy-security.0 | 2021-04-06 17:56:41.355 | error | at Station.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/http/station.js:177:43)
eufy-security.0 | 2021-04-06 17:56:41.355 | error | (1206) TypeError: this.hub.devices is not iterable
eufy-security.0 | 2021-04-06 17:56:41.353 | error | (1206) unhandled promise rejection: this.hub.devices is not iterable
eufy-security.0 | 2021-04-06 17:56:41.352 | error | (1206) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
eufy-security.0 | 2021-04-06 17:56:40.235 | info | (1206) Refresh data from cloud and schedule next refresh.
eufy-security.0 | 2021-04-06 17:56:40.042 | info | (1206) starting. Version 0.5.2 in /opt/iobroker/node_modules/iobroker.eufy-security, node: v12.22.0, js-controller: 3.2.16
```

Cheers

**Comment by 89jd** [comment]
Fixed by enabling admin access to account!
