### ISSUE TITLE
Door lock failed and broke the connection because of null ack

### ISSUE THREAD

**Issue by lightgoleft** [bropat/ioBroker.eufy-security#144]
The smart door lock failed to handle switch to lock/unlock because js call returned a null ack. 

log:
```


eufy-security.0 | 2021-07-06 08:43:07.204 | error | (15193) Cannot read property 'ack' of null
eufy-security.0 | 2021-07-06 08:43:07.204 | error | at fulfilled (/opt/iobroker/node_modules/iobroker.eufy-security/build/lib/eufy-security/eufy-security.js:5:58)
eufy-security.0 | 2021-07-06 08:43:07.204 | error | at Generator.next (<anonymous>)
eufy-security.0 | 2021-07-06 08:43:07.204 | error | at EufySecurity.<anonymous> (/opt/iobroker/node_modules/iobroker.eufy-security/build/lib/eufy-security/eufy-security.js:219:44)
eufy-security.0 | 2021-07-06 08:43:07.204 | error | (15193) TypeError: Cannot read property 'ack' of null
eufy-security.0 | 2021-07-06 08:43:07.204 | error | (15193) unhandled promise rejection: Cannot read property 'ack' of null
eufy-security.0 | 2021-07-06 08:43:07.203 | error | (15193) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch bloc

host.iobroker | 2021-07-06 08:43:09.403 | error | instance system.adapter.eufy-security.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

eufy-security.0 | 2021-07-06 08:43:09.385 | error | (15193) DB closed
eufy-security.0 | 2021-07-06 08:43:09.385 | error | at TCP.<anonymous> (net.js:675:12)
eufy-security.0 | 2021-07-06 08:43:09.385 | error | at Socket.emit (events.js:314:20)
eufy-security.0 | 2021-07-06 08:43:09.385 | error | at Object.onceWrapper (events.js:421:26)
eufy-security.0 | 2021-07-06 08:43:09.385 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:150:20)
eufy-security.0 | 2021-07-06 08:43:09.385 | error | at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:183:25)
eufy-security.0 | 2021-07-06 08:43:09.385 | error | (15193) Error: DB closed
eufy-security.0 | 2021-07-06 08:43:09.385 | error | (15193) unhandled promise rejection: DB closed
eufy-security.0 | 2021-07-06 08:43:09.385 | error | (15193) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
eufy-security.0 | 2021-07-06 08:43:09.385 | error | (15193) DB closed
eufy-security.0 | 2021-07-06 08:43:09.384 | error | at TCP.<anonymous> (net.js:675:12)
eufy-security.0 | 2021-07-06 08:43:09.384 | error | at Socket.emit (events.js:314:20)
eufy-security.0 | 2021-07-06 08:43:09.384 | error | at Object.onceWrapper (events.js:421:26)
eufy-security.0 | 2021-07-06 08:43:09.384 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:150:20)
eufy-security.0 | 2021-07-06 08:43:09.384 | error | at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:183:25)
eufy-security.0 | 2021-07-06 08:43:09.384 | error | (15193) Error: DB closed
eufy-security.0 | 2021-07-06 08:43:09.384 | error | (15193) unhandled promise rejection: DB closed
eufy-security.0 | 2021-07-06 08:43:09.384 | error | (15193) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
eufy-security.0 | 2021-07-06 08:43:09.383 | error | (15193) DB closed
eufy-security.0 | 2021-07-06 08:43:09.383 | error | at TCP.<anonymous> (net.js:675:12)
eufy-security.0 | 2021-07-06 08:43:09.383 | error | at Socket.emit (events.js:314:20)
eufy-security.0 | 2021-07-06 08:43:09.383 | error | at Object.onceWrapper (events.js:421:26)
eufy-security.0 | 2021-07-06 08:43:09.383 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:150:20)
eufy-security.0 | 2021-07-06 08:43:09.383 | error | at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:183:25)
eufy-security.0 | 2021-07-06 08:43:09.383 | error | (15193) Error: DB closed
eufy-security.0 | 2021-07-06 08:43:09.382 | error | (15193) unhandled promise rejection: DB closed
eufy-security.0 | 2021-07-06 08:43:09.382 | error | (15193) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch bloc

**Comment by lightgoleft** [comment]
The issue is gone after update to 0.55
