### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by t0m5k1** [bropat/ioBroker.eufy-security#170]

**Comment by t0m5k1** [comment]
I'm totally new to node and I've tried all manner of commands and it's not running!

What do I do.
Here are some of my attempts:

❯ npm start iobroker.eufy-security
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/t0m5k1/.npm/_logs/2021-09-18T10_49_26_431Z-debug.log
❯ iobroker
zsh: command not found: iobroker
❯ ll /opt
total 28K
drwxr-xr-x 5 root root 4.0K Aug  6 11:00 authy/
drwxr-xr-x 6 root root  12K Sep 10 18:21 dropbox/
drwxr-xr-x 7 root root 4.0K Sep  6 18:24 spotify/
drwxr-xr-x 4 root root 4.0K Sep  1 17:46 teamviewer/
drwxr-xr-x 2 root root 4.0K Sep 10 18:21 tor-browser/
❯ npm uninstall iobroker.eufy-security

removed 71 packages, and audited 1 package in 443ms

found 0 vulnerabilities
❯ sudo npm i iobroker.eufy-security
[sudo] password for t0m5k1: 

added 71 packages, and audited 72 packages in 12s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
❯ ll /opt
total 28K
drwxr-xr-x 5 root root 4.0K Aug  6 11:00 authy/
drwxr-xr-x 6 root root  12K Sep 10 18:21 dropbox/
drwxr-xr-x 7 root root 4.0K Sep  6 18:24 spotify/
drwxr-xr-x 4 root root 4.0K Sep  1 17:46 teamviewer/
drwxr-xr-x 2 root root 4.0K Sep 10 18:21 tor-browser/
❯ iobroker
zsh: command not found: iobroker
❯ sudo find / -name "iobroker"
/home/t0m5k1/node_modules/@types/iobroker
find: ‘/run/user/1000/gvfs’: Permission denied
❯ npm start iobroker.eufy-security
npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/t0m5k1/.npm/_logs/2021-09-18T11_00_28_400Z-debug.log
❯ npm run
❯ sudo npm run
❯ mpn test
zsh: command not found: mpn
❯ npm test
npm ERR! Missing script: "test"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/t0m5k1/.npm/_logs/2021-09-18T11_02_00_846Z-debug.log
❯ npm -g list
/usr/lib
├── asar@3.1.0
├── grunt-cli@1.4.3
├── node-gyp@8.1.0
├── nopt@5.0.0
├── npm@7.24.0
├── semver@7.3.5
└── yarn@1.22.11

❯ node iobroker.eufy-security
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/home/t0m5k1/iobroker.eufy-security'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
❯ npm -g list
/usr/lib
├── asar@3.1.0
├── grunt-cli@1.4.3
├── node-gyp@8.1.0
├── nopt@5.0.0
├── npm@7.24.0
├── semver@7.3.5
└── yarn@1.22.11

as you can see I have ZERO clue how to get this to work

will someone please help me?
I've seen the Dev be active here since I posted but perhaps a new user is not important i don't know
