### ISSUE TITLE
Getting Unhandled promise rejection errors

### ISSUE THREAD

**Issue by gojojo77** [bropat/ioBroker.eufy-security#32]
Thanks for your work on this adapter.

I have installed it and am trying it out.

The adapter starts fine, but then I get some errors, and the adapter restarts over and over again. Here is the log:

```
host.[REDACTED] | 2020-12-24 17:24:55.513 | info | Restart adapter system.adapter.eufy-security.0 because enabled
-- | -- | -- | --
host.[REDACTED] | 2020-12-24 17:24:55.513 | info | instance system.adapter.eufy-security.0 terminated with code 0 (NO_ERROR)
eufy-security.0 | 2020-12-24 17:24:55.011 | error | (420) Error: Request failed with status code 404 at createError (/opt/iobroker/node_modules/iobroker.eufy-security/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/no
eufy-security.0 | 2020-12-24 17:24:55.010 | error | (420) unhandled promise rejection: Request failed with status code 404
eufy-security.0 | 2020-12-24 17:24:55.010 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
eufy-security.0 | 2020-12-24 17:24:54.974 | info | (420) Terminated (NO_ERROR): Without reason
eufy-security.0 | 2020-12-24 17:24:54.973 | info | (420) terminating
eufy-security.0 | 2020-12-24 17:24:54.964 | error | (420) Error: Request failed with status code 404 at createError (/opt/iobroker/node_modules/iobroker.eufy-security/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/no
eufy-security.0 | 2020-12-24 17:24:54.964 | error | (420) unhandled promise rejection: Request failed with status code 404
eufy-security.0 | 2020-12-24 17:24:54.963 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
eufy-security.0 | 2020-12-24 17:24:54.961 | info | (420) Disconnect from station [REDACTED].
eufy-security.0 | 2020-12-24 17:24:54.958 | error | (420) Error: Request failed with status code 404 at createError (/opt/iobroker/node_modules/iobroker.eufy-security/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/no
eufy-security.0 | 2020-12-24 17:24:54.956 | error | (420) unhandled promise rejection: Request failed with status code 404
eufy-security.0 | 2020-12-24 17:24:54.955 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
eufy-security.0 | 2020-12-24 17:24:53.031 | info | (420) state eufy-security.0.[REDACTED].station.lan_ip_address changed: [REDACTED] (ack = true)
eufy-security.0 | 2020-12-24 17:24:53.022 | info | (420) state eufy-security.0.[REDACTED].station.lan_ip_address changed: [REDACTED] (ack = true)
eufy-security.0 | 2020-12-24 17:24:52.027 | info | (420) Refresh data from cloud and schedule next refresh.
eufy-security.0 | 2020-12-24 17:24:51.902 | info | (420) starting. Version 0.0.8 in /opt/iobroker/node_modules/iobroker.eufy-security, node: v12.20.0, js-controller: 3.1.6
host.[REDACTED] | 2020-12-24 17:24:50.754 | info | instance system.adapter.eufy-security.0 started with pid 420
info.0 | 2020-12-24 17:24:49.612 | info | (119) starting. Version 1.7.10 in /opt/iobroker/node_modules/iobroker.info, node: v12.20.0, js-controller: 3.1.6
```

I did see it once get some data from the camera, but then it reverted back to this behavior.

Do you have any ideas what this may be?

Thanks

**Versions:**  
 - Adapter version: 0.0.8
 - JS-Controller version: 3.1.6
 - Node version: v12.20.0
 - Operating system: Using docker: buanet/iobroker:latest

**Comment by bropat** [comment]
@gojojo77 Please enable debugging according to [this](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug) guide, reproduce the problem and send me the logs (**Attention:** The logs contain sensitive data. Please redact!).

**Comment by bropat** [comment]
@gojojo77 
Please follow the instructions as described above and let me know. If I don't hear from you in the next few days I will close this issue.

Thanks for the understanding.

**Comment by gojojo77** [comment]
Thanks @bropat , sorry for the delay, got busy over Xmas.

There was a lot of sensitive data in the logs like you mentioned. Hopefully it is not too heavily redacted to be useful.

It does seem to be retrieving data from the cameras (I can see the values in the non-redacted logs and iobroker).

So maybe the error is not really an issue that stops it working? If so, feel free to close the ticket.

```
2020-12-29 12:52:57.061 - info: eufy-security.0 (490) starting. Version 0.0.9 in /opt/iobroker/node_modules/iobroker.eufy-security, node: v12.20.0, js-controller: 3.1.6
2020-12-29 12:52:57.137 - debug: eufy-security.0 (490) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
2020-12-29 12:52:57.149 - debug: eufy-security.0 (490) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
2020-12-29 12:52:57.156 - debug: eufy-security.0 (490) onReady(): Load previous api_base: https://security-app.eufylife.com/v1
2020-12-29 12:52:57.156 - debug: eufy-security.0 (490) onReady(): Load previous login_hash: [REDACTED]
2020-12-29 12:52:57.157 - debug: eufy-security.0 (490) onReady(): Load previous token: [REDACTED] token_expiration: [REDACTED]
2020-12-29 12:52:57.159 - debug: eufy-security.0 (490) API.authenticate(): token: [REDACTED] token_expiration: Thu Jan 28 2021 12:48:03 GMT+1300 (New Zealand Daylight Time)
2020-12-29 12:52:57.209 - info: eufy-security.0 (490) Refresh data from cloud and schedule next refresh.
2020-12-29 12:52:57.212 - debug: eufy-security.0 (490) API.request(): method: post endpoint: app/get_hub_list baseUrl: https://security-app.eufylife.com/v1 token: [REDACTED] data: undefined headers: {"app_version":[REDACTED]}
2020-12-29 12:52:58.196 - debug: eufy-security.0 (490) API.updateDeviceInfo(): stations - Response: {"code":0,"msg":"Succeed.",[REDACTED]}
2020-12-29 12:52:58.198 - debug: eufy-security.0 (490) API.updateDeviceInfo(): stations - element: {[REDACTED]}
2020-12-29 12:52:58.199 - debug: eufy-security.0 (490) API.updateDeviceInfo(): stations - device_type: 0
2020-12-29 12:52:58.199 - debug: eufy-security.0 (490) EufySecurity.handleHubs(): hubs: 1
2020-12-29 12:52:58.200 - debug: eufy-security.0 (490) Station.loadParameters(): station_sn: [REDACTED]
2020-12-29 12:52:58.201 - debug: eufy-security.0 (490) EufySecurity.handleHubs(): stations: 1
2020-12-29 12:52:58.201 - debug: eufy-security.0 (490) handleStations(): count: 1
2020-12-29 12:52:58.203 - debug: eufy-security.0 (490) API.request(): method: post endpoint: app/get_devs_list baseUrl: https://security-app.eufylife.com/v1 token: [REDACTED] data: undefined headers: {"app_version":[REDACTED]}
2020-12-29 12:52:58.232 - info: eufy-security.0 (490) state eufy-security.0.[REDACTED].station.lan_ip_address changed: [REDACTED] (ack = true)
2020-12-29 12:52:58.286 - info: eufy-security.0 (490) state eufy-security.0.[REDACTED].station.lan_ip_address changed: [REDACTED] (ack = true)
2020-12-29 12:52:59.381 - debug: eufy-security.0 (490) API.updateDeviceInfo(): devices - Response: {"code":0,"msg":"Succeed.",[REDACTED]}
2020-12-29 12:52:59.383 - debug: eufy-security.0 (490) EufySecurity.handleDevices(): devices: 4
2020-12-29 12:52:59.384 - debug: eufy-security.0 (490) Device.loadParameters(): device_sn: [REDACTED]
2020-12-29 12:52:59.385 - debug: eufy-security.0 (490) Device.loadParameters(): device_sn: [REDACTED]
2020-12-29 12:52:59.385 - debug: eufy-security.0 (490) Device.loadParameters(): device_sn: [REDACTED]
2020-12-29 12:52:59.386 - debug: eufy-security.0 (490) Device.loadParameters(): device_sn: [REDACTED]
2020-12-29 12:52:59.386 - debug: eufy-security.0 (490) EufySecurity.handleDevices(): devices: 4
2020-12-29 12:52:59.387 - debug: eufy-security.0 (490) handleDevices(): count: 4
2020-12-29 12:52:59.392 - debug: eufy-security.0 (490) API.request(): method: get endpoint: app/trust_device/list baseUrl: https://security-app.eufylife.com/v1 token: [REDACTED] data: undefined headers: {"app_version":[REDACTED]}
2020-12-29 12:53:00.233 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-12-29 12:53:00.233 - error: eufy-security.0 (490) unhandled promise rejection: Request failed with status code 404
2020-12-29 12:53:00.234 - error: eufy-security.0 (490) Error: Request failed with status code 404
at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:326:22)
at endReadableNT (_stream_readable.js:1241:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-12-29 12:53:00.236 - info: eufy-security.0 (490) Disconnect from station [REDACTED].
2020-12-29 12:53:00.240 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-12-29 12:53:00.241 - error: eufy-security.0 (490) unhandled promise rejection: Request failed with status code 404
2020-12-29 12:53:00.242 - error: eufy-security.0 (490) Error: Request failed with status code 404
at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:326:22)
at endReadableNT (_stream_readable.js:1241:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-12-29 12:53:00.250 - info: eufy-security.0 (490) terminating
2020-12-29 12:53:00.251 - info: eufy-security.0 (490) Terminated (NO_ERROR): Without reason
```

**Comment by bropat** [comment]
@gojojo77
Can not understand this error at the moment. It looks like an HTTP endpoint of the 2FA does not exist in your case.
Do you have 2FA enabled?

**Comment by gojojo77** [comment]
@bropat Thanks. No 2FA is off. I can try with it on...

**Comment by gojojo77** [comment]
@bropat Thanks for your help on this. But think I will try some other ways to control my cameras.

2FA did not make any difference. I might reset my Eufy setup soon, must be something weird with it, and see if that helps.

So please close for now, to save you spending anymore time on it.

Have a good new year :-)

**Comment by bropat** [comment]
@gojojo77 

ok. You too :)
